// user-center-react-frontend/src/pages/user/profiles/components/GenderDisplay.tsx
import { ManOutlined, UserOutlined, WomanOutlined } from "@ant-design/icons";
import { Space, Typography } from "antd";
import React from "react";

const { Text } = Typography;

interface GenderDisplayProps {
  gender?: number;
}

const GenderDisplay: React.FC<GenderDisplayProps> = ({ gender }) => {
  if (gender === 0) {
    return (
      <Space>
        <WomanOutlined style={{ color: "#eb2f96" }} />
        <Text>女</Text>
      </Space>
    );
  }
  if (gender === 1) {
    return (
      <Space>
        <ManOutlined style={{ color: "#1890ff" }} />
        <Text>男</Text>
      </Space>
    );
  }
  if (gender === 2) {
    return (
      <Space>
        <UserOutlined style={{ color: "rgb(0 0 0 / 25%)" }} />
        <Text type="secondary">未知</Text>
      </Space>
    );
  }
  return <Text type="secondary">未设置</Text>;
};

export default GenderDisplay;

// user-center-vue-frontend/src/views/user/profiles/modules/gender-display.vue
<script setup lang="ts">
/**
 * 性别显示组件
 */
import { WomanOutlined, ManOutlined, UserOutlined } from "@ant-design/icons-vue";

defineOptions({ name: "GenderDisplay" });

defineProps<{
    gender?: number;
}>();
</script>

<template>
    <a-space v-if="gender === 0">
        <WomanOutlined style="color: #eb2f96" />
        <a-typography-text>女</a-typography-text>
    </a-space>
    <a-space v-else-if="gender === 1">
        <ManOutlined style="color: #1890ff" />
        <a-typography-text>男</a-typography-text>
    </a-space>
    <a-space v-else-if="gender === 2">
        <UserOutlined style="color: rgb(0 0 0 / 25%)" />
        <a-typography-text type="secondary">未知</a-typography-text>
    </a-space>
    <a-typography-text v-else type="secondary">未设置</a-typography-text>
</template>

<style scoped></style>
