// user-center-react-frontend/src/pages/user/settings/components/UserAvatar.tsx
import { PictureOutlined, UserOutlined } from "@ant-design/icons";
import { useModel } from "@umijs/max";
import type { UploadProps } from "antd";
import { Avatar, Card, Space, Typography, Upload } from "antd";
import { createStyles } from "antd-style";
import React from "react";
import { DEFAULT_AVATAR } from "@/constants";
import { useUserOperations } from "@/hooks/useUserOperations";
import { authStore } from "@/stores/auth";

const { Text, Title } = Typography;

const useStyles = createStyles(({ token }) => ({
  cardIcon: {
    fontSize: 16,
    color: token.colorPrimary,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: 600,
  },
  avatarSection: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "32px 24px",
    textAlign: "center",
  },
  avatarMeta: {
    margin: "20px 0",
  },
  avatarName: {
    marginBottom: "8px !important",
  },
  avatarAccount: {
    fontSize: 14,
  },
  avatarUploadBtn: {
    display: "inline-block",
    padding: "10px 32px",
    color: "#fff",
    textDecoration: "none",
    cursor: "pointer",
    background: token.colorPrimary,
    borderRadius: 8,
    transition: "all 0.3s",
    "&:hover": {
      color: "#fff",
      boxShadow: "0 6px 16px rgb(24 144 255 / 30%)",
      transform: "translateY(-2px)",
    },
  },
  avatarTip: {
    display: "block",
    marginTop: 16,
    fontSize: 12,
  },
}));

const UserAvatar: React.FC = () => {
  const { initialState } = useModel("@@initialState");
  const currentUser = initialState?.auth?.user;
  const { uploading, handleAvatarUpload } = useUserOperations();
  const { styles } = useStyles();

  const beforeUpload: UploadProps["beforeUpload"] = async (file) => {
    if (!file) return false;
    try {
      const avatarUploadResult = await handleAvatarUpload(file);
      if (avatarUploadResult) {
        await authStore.refreshCurrentUser();
        return true;
      }
      return false;
    } catch (error) {
      console.error("头像上传失败:", error);
      return false;
    }
  };

  return (
    <Card bordered>
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: 8,
          marginBottom: 4,
        }}
      >
        <PictureOutlined className={styles.cardIcon} />
        <span className={styles.cardTitle}>用户头像</span>
      </div>
      <div className={styles.avatarSection}>
        <Avatar
          size={120}
          src={currentUser?.userAvatar || DEFAULT_AVATAR}
          icon={<UserOutlined />}
        />
        <div className={styles.avatarMeta}>
          <Title level={4} className={styles.avatarName}>
            {currentUser?.userName || "未设置昵称"}
          </Title>
          <Text type="secondary" className={styles.avatarAccount}>
            @{currentUser?.userAccount || ""}
          </Text>
        </div>
        <Upload
          beforeUpload={beforeUpload}
          disabled={uploading}
          showUploadList={false}
          accept="image/*"
        >
          <a className={styles.avatarUploadBtn}>
            {uploading ? "上传中..." : "更换头像"}
          </a>
        </Upload>
        <Text type="secondary" className={styles.avatarTip}>
          支持 JPG、JPEG、PNG、GIF 格式
          <br />
          大小不超过 2MB
        </Text>
      </div>
    </Card>
  );
};

export default UserAvatar;

// user-center-vue-frontend/src/views/user/settings/moudels/user-avatar.vue
<script setup lang="ts">
/**
 * 用户头像卡片
 */
import { PictureOutlined, UserOutlined } from "@ant-design/icons-vue";
import { useAuthStore } from "@/stores/auth.ts";
import { storeToRefs } from "pinia";
import type { UploadProps } from "ant-design-vue";
import { useUserOperations } from "@/composable/user-operations.ts";

defineOptions({ name: "UserAvatar" });

const authStore = useAuthStore();
// storeToRefs 解构后仍保持响应性
const { user: loginUser } = storeToRefs(authStore);

const userOperations = useUserOperations();

/**
 * 处理头像上传
 *
 * @param file 选择的文件对象
 */
const handleAvatarUpload: UploadProps["beforeUpload"] = async (file) => {
    if (!file) {
        return false;
    }
    try {
        const avatarUploadResult = await userOperations.handleAvatarUpload(file);
        if (avatarUploadResult) {
            // 上传成功后刷新用户信息以显示新头像
            await authStore.refreshCurrentUser();
            return true;
        } else {
            return false; // 阻止默认上传行为
        }
    } catch (error) {
        console.error("头像上传失败:", error);
        return false;
    }
};
</script>

<template>
    <a-card :bordered="true">
        <template #title>
            <a-space>
                <PictureOutlined class="card-icon" />
                <span class="card-title">用户头像</span>
            </a-space>
        </template>
        <div class="avatar-section">
            <a-avatar :size="120" :src="loginUser?.userAvatar">
                <template #icon>
                    <UserOutlined />
                </template>
            </a-avatar>

            <div class="avatar-meta">
                <a-typography-title :level="4" class="avatar-name">
                    {{ loginUser?.userName || "未设置昵称" }}
                </a-typography-title>
                <a-typography-text class="avatar-account" type="secondary">
                    @{{ loginUser?.userAccount || "" }}
                </a-typography-text>
            </div>

            <a-upload
                :before-upload="handleAvatarUpload"
                :disabled="userOperations.uploading.value"
                :show-upload-list="false"
                accept="image/*"
            >
                <a class="avatar-upload-btn">
                    {{ userOperations.uploading.value ? "上传中..." : "更换头像" }}
                </a>
            </a-upload>

            <a-typography-text class="avatar-tip" type="secondary">
                支持 JPG、JPEG、PNG、GIF 格式<br />大小不超过 2MB
            </a-typography-text>
        </div>
    </a-card>
</template>

<style scoped>
.card-icon {
    font-size: 16px;
    color: var(--ant-color-primary);
}

.card-title {
    font-size: 16px;
    font-weight: 600;
}

.avatar-section {
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 32px 24px;
    text-align: center;
}

.avatar-meta {
    margin: 20px 0;
}

.avatar-name {
    margin-bottom: 8px !important;
}

.avatar-account {
    font-size: 14px;
}

.avatar-upload-btn {
    display: inline-block;
    padding: 10px 32px;
    color: #fff;
    text-decoration: none;
    cursor: pointer;
    background: var(--ant-color-primary);
    border-radius: 8px;
    transition: all 0.3s;
}

.avatar-upload-btn:hover {
    color: #fff;
    box-shadow: 0 6px 16px rgb(24 144 255 / 30%);
    transform: translateY(-2px);
}

.avatar-tip {
    display: block;
    margin-top: 16px;
    font-size: 12px;
}
</style>
