// user-center-vue-frontend/src/views/auth/login/index.vue
<script setup lang="ts">
/**
 * 用户登录页面.
 */
import { ref, reactive } from "vue";
import { useRouter } from "vue-router";
import { ROUTES } from "@/constants/routes.ts";
import { getSafeAuthRedirect } from "@/utils/redirect/auth-redirect";
import {
    LockOutlined,
    MailOutlined,
    MobileOutlined,
    SafetyCertificateOutlined,
    UserOutlined,
} from "@ant-design/icons-vue";
import type { Api } from "@/types/api/typings";
import {
    BusinessCode,
    CODE_REGEX,
    PASSWORD_MAX_LENGTH,
    PASSWORD_MIN_LENGTH,
    PHONE_REGEX,
    PWD_REGEX,
} from "@/constants";
import type { Rule } from "ant-design-vue/es/form";
import type { AxiosResponse } from "axios";
import { userEmailLogin, userLogin, userPhoneLogin, userEmailResetPwd, userPhoneResetPwd } from "@/api/user.ts";
import { useAuthStore } from "@/stores/auth.ts";
import type { FormInstance } from "ant-design-vue";
import { useCaptchaSender } from "@/composable/send-captcha.ts";

defineOptions({ name: "UserLogin" });

const router = useRouter();
const authStore = useAuthStore();

const labelCol = { span: 0 };
const wrapperCol = { span: 24 };

// 当前激活的登录方式
const activeKey = ref("account");

// 账号注册表单引用
const accountFormRef = ref<FormInstance>();
// 账号注册表单数据
const accountForm = reactive<Api.User.UserLoginRequest>({
    userAccount: "",
    userPassword: "",
});

// 邮箱注册表单引用
const emailFormRef = ref<FormInstance>();
// 邮箱注册表单数据
const emailForm = reactive<Api.User.UserEmailLoginRequest>({
    userEmail: "",
    captchaCode: "",
});

// 手机号注册表单引用
const phoneFormRef = ref<FormInstance>();
// 手机号注册表单数据
const phoneForm = reactive<Api.User.UserPhoneLoginRequest>({
    userPhone: "",
    captchaCode: "",
});

type SubmitState = {
    accountBtn: boolean;
    emailBtn: boolean;
    phoneBtn: boolean;
    emailResetBtn: boolean;
    phoneResetBtn: boolean;
};

// 提交状态
const submitting = reactive<SubmitState>({
    accountBtn: false,
    emailBtn: false,
    phoneBtn: false,
    emailResetBtn: false,
    phoneResetBtn: false,
});

// 表单验证规则
const FormRules: Record<string, Rule[]> = {
    userAccount: [
        { required: true, message: "登录账号是必填项!", trigger: "blur" },
        { min: 4, message: "账号长度不小于 4 位!", trigger: "blur" },
        { max: 16, message: "账号长度不大于 16 位!", trigger: "blur" },
    ],
    userPassword: [
        { required: true, message: "登录密码是必填项!", trigger: "blur" },
        { min: PASSWORD_MIN_LENGTH, message: `密码长度不小于 ${PASSWORD_MIN_LENGTH} 位!`, trigger: "blur" },
        { max: PASSWORD_MAX_LENGTH, message: `密码长度不大于 ${PASSWORD_MAX_LENGTH} 位!`, trigger: "blur" },
        { pattern: PWD_REGEX, message: "密码需包含大小写字母、数字和特殊字符", trigger: "blur" },
    ],
    checkPassword: [
        { required: true, message: "请确认登录密码!", trigger: "blur" },
        {
            validator: (_rule, value) => {
                if (value !== accountForm.userPassword) {
                    return Promise.reject("两次输入的密码不一致!");
                }
                return Promise.resolve();
            },
            trigger: "blur",
        },
    ],
    userEmail: [
        { required: true, message: "邮箱地址是必填项!", trigger: "blur" },
        { type: "email", message: "邮箱格式不正确!", trigger: "blur" },
    ],
    userPhone: [
        { required: true, message: "手机号是必填项!", trigger: "blur" },
        { pattern: PHONE_REGEX, message: "手机号格式不正确!", trigger: "blur" },
    ],
    captchaCode: [
        { required: true, message: "验证码是必填项!", trigger: "blur" },
        // 验证码格式为 6 位数字
        { pattern: CODE_REGEX, message: "验证码格式不正确!", trigger: "blur" },
    ],
};

type LoginApiFunction<TRequest> = (data: TRequest) => Promise<AxiosResponse<Api.User.UserLoginResponse>>;

const createSubmitHandler =
    <TRequest>(
        apiFn: LoginApiFunction<TRequest>,
        formData: TRequest,
        submitState: SubmitState,
        submitKey: keyof SubmitState
    ) =>
    async () => {
        submitState[submitKey] = true;
        try {
            const { data } = await apiFn(formData);
            if (data.code === BusinessCode.SUCCESS && data.success) {
                const userLoginVo = data.data;
                authStore.markAuthenticated(userLoginVo);
                // 路由跳转到上次的页面或者首页
                const redirectPath = getSafeAuthRedirect(router.currentRoute.value.query.redirect);
                await router.push(redirectPath);
            }
        } catch (error) {
            console.log(`登录异常：${error}`);
        } finally {
            submitState[submitKey] = false;
        }
    };

/**
 * 处理账号登录提交
 */
const handleAccountSubmit = async () => {
    await accountFormRef.value?.validate();
    await createSubmitHandler(userLogin, accountForm, submitting, "accountBtn")();
};

/**
 * 处理邮箱登录提交
 */
const handleEmailSubmit = async () => {
    await emailFormRef.value?.validate();
    await createSubmitHandler(userEmailLogin, emailForm, submitting, "emailBtn")();
};

/**
 * 处理手机号登录提交
 */
const handlePhoneSubmit = async () => {
    await phoneFormRef.value?.validate();
    await createSubmitHandler(userPhoneLogin, phoneForm, submitting, "phoneBtn")();
};

// 邮箱验证码发送器实例（登录）
const emailCaptchaSender = useCaptchaSender("EMAIL", "LOGIN", () => emailForm.userEmail, "请输入邮箱地址以获取验证码");

// 手机号验证码发送器实例（登录）
const phoneCaptchaSender = useCaptchaSender("SMS", "LOGIN", () => phoneForm.userPhone, "请输入手机号以获取验证码");

// ========== 忘记密码弹窗相关 ==========
// 控制弹窗显示
const showResetModal = ref(false);
const resetActiveKey = ref("email");

// 重置 - 邮箱表单
const emailResetFormRef = ref<FormInstance>();
const emailResetForm = reactive<{ userEmail: string; captchaCode: string; newPassword: string; checkPassword: string }>(
    {
        userEmail: "",
        captchaCode: "",
        newPassword: "",
        checkPassword: "",
    }
);

// 重置 - 手机表单
const phoneResetFormRef = ref<FormInstance>();
const phoneResetForm = reactive<{ userPhone: string; captchaCode: string; newPassword: string; checkPassword: string }>(
    {
        userPhone: "",
        captchaCode: "",
        newPassword: "",
        checkPassword: "",
    }
);

// 验证码发送器（重置场景）
const emailResetCaptchaSender = useCaptchaSender(
    "EMAIL",
    "RESET_PWD",
    () => emailResetForm.userEmail,
    "请输入邮箱地址以获取验证码"
);
const phoneResetCaptchaSender = useCaptchaSender(
    "SMS",
    "RESET_PWD",
    () => phoneResetForm.userPhone,
    "请输入手机号以获取验证码"
);

// 重置表单校验规则
const emailResetRules: Record<string, Rule[]> = {
    userEmail: FormRules.userEmail!,
    captchaCode: FormRules.captchaCode!,
    newPassword: FormRules.userPassword!,
    checkPassword: [
        { required: true, message: "请确认新密码!", trigger: "blur" },
        {
            validator: (_rule, value) => {
                if (value !== emailResetForm.newPassword) {
                    return Promise.reject("两次输入的密码不一致!");
                }
                return Promise.resolve();
            },
            trigger: "blur",
        },
    ],
};

const phoneResetRules: Record<string, Rule[]> = {
    userPhone: FormRules.userPhone!,
    captchaCode: FormRules.captchaCode!,
    newPassword: FormRules.userPassword!,
    checkPassword: [
        { required: true, message: "请确认新密码!", trigger: "blur" },
        {
            validator: (_rule, value) => {
                if (value !== phoneResetForm.newPassword) {
                    return Promise.reject("两次输入的密码不一致!");
                }
                return Promise.resolve();
            },
            trigger: "blur",
        },
    ],
};

// 处理邮箱重置提交
const handleEmailResetSubmit = async () => {
    await emailResetFormRef.value?.validate();
    submitting.emailResetBtn = true;
    try {
        const payload = {
            userEmail: emailResetForm.userEmail,
            captchaCode: emailResetForm.captchaCode,
            newPassword: emailResetForm.newPassword,
            checkPassword: emailResetForm.checkPassword,
        } as Api.User.UserEmailResetPwdRequest;

        const { data } = await userEmailResetPwd(payload);
        if (data.code === BusinessCode.SUCCESS && data.success) {
            showResetModal.value = false;
            // 清理表单
            emailResetForm.userEmail = "";
            emailResetForm.captchaCode = "";
            emailResetForm.newPassword = "";
            emailResetForm.checkPassword = "";
        }
    } catch (error) {
        console.log(`重置密码异常：${error}`);
    } finally {
        submitting.emailResetBtn = false;
    }
};

// 处理手机号重置提交
const handlePhoneResetSubmit = async () => {
    await phoneResetFormRef.value?.validate();
    submitting.phoneResetBtn = true;
    try {
        const payload = {
            userPhone: phoneResetForm.userPhone,
            captchaCode: phoneResetForm.captchaCode,
            newPassword: phoneResetForm.newPassword,
            checkPassword: phoneResetForm.checkPassword,
        } as Api.User.UserPhoneResetPwdRequest;

        const { data } = await userPhoneResetPwd(payload);
        if (data.code === BusinessCode.SUCCESS && data.success) {
            showResetModal.value = false;
            phoneResetForm.userPhone = "";
            phoneResetForm.captchaCode = "";
            phoneResetForm.newPassword = "";
            phoneResetForm.checkPassword = "";
        }
    } catch (error) {
        console.log(`重置密码异常：${error}`);
    } finally {
        submitting.phoneResetBtn = false;
    }
};
</script>

<template>
    <div id="user-login">
        <a-card :bordered="false" class="login-card" title="登录新账号">
            <template #extra>
                <div class="login-footer">
                    <span>还没有账号？</span>
                    <router-link :to="ROUTES.REGISTER.path">立即注册</router-link>
                    <span style="margin: 0 8px">|</span>
                    <a @click="showResetModal = true">忘记密码</a>
                </div>
            </template>
            <a-tabs v-model:activeKey="activeKey" centered>
                <!-- 账号登录 -->
                <a-tab-pane key="account" tab="账号密码">
                    <a-form
                        ref="accountFormRef"
                        :model="accountForm"
                        @finish="handleAccountSubmit"
                        :label-col="labelCol"
                        :wrapper-col="wrapperCol"
                    >
                        <a-form-item name="userAccount" :rules="FormRules.userAccount">
                            <a-input
                                v-model:value="accountForm.userAccount"
                                size="large"
                                placeholder="请输入登录账号"
                                allow-clear
                            >
                                <template #prefix><UserOutlined /></template>
                            </a-input>
                        </a-form-item>
                        <a-form-item name="userPassword" :rules="FormRules.userPassword">
                            <a-input-password
                                v-model:value="accountForm.userPassword"
                                size="large"
                                placeholder="请输入登录密码"
                                allow-clear
                            >
                                <template #prefix><LockOutlined /></template>
                            </a-input-password>
                        </a-form-item>
                        <a-form-item>
                            <a-button
                                type="primary"
                                html-type="submit"
                                size="large"
                                block
                                :loading="submitting.accountBtn"
                            >
                                登录
                            </a-button>
                        </a-form-item>
                    </a-form>
                </a-tab-pane>

                <!-- 邮箱登录 -->
                <a-tab-pane key="email" tab="邮箱登录">
                    <a-form
                        ref="emailFormRef"
                        :model="emailForm"
                        @finish="handleEmailSubmit"
                        :label-col="labelCol"
                        :wrapper-col="wrapperCol"
                    >
                        <a-form-item name="userEmail" :rules="FormRules.userEmail">
                            <a-input
                                v-model:value="emailForm.userEmail"
                                size="large"
                                placeholder="请输入邮箱地址"
                                allow-clear
                            >
                                <template #prefix><MailOutlined /></template>
                            </a-input>
                        </a-form-item>
                        <a-form-item name="captchaCode" :rules="FormRules.captchaCode">
                            <div class="captcha-wrapper">
                                <a-input
                                    v-model:value="emailForm.captchaCode"
                                    size="large"
                                    placeholder="请输入验证码"
                                    allow-clear
                                >
                                    <template #prefix><SafetyCertificateOutlined /></template>
                                </a-input>
                                <a-button
                                    size="large"
                                    :disabled="emailCaptchaSender.countdown.value > 0"
                                    :loading="emailCaptchaSender.sending.value"
                                    @click="emailCaptchaSender.send()"
                                >
                                    {{
                                        emailCaptchaSender.countdown.value > 0
                                            ? `${emailCaptchaSender.countdown.value}秒后重试`
                                            : "获取验证码"
                                    }}
                                </a-button>
                            </div>
                        </a-form-item>
                        <a-form-item>
                            <a-button
                                type="primary"
                                html-type="submit"
                                size="large"
                                block
                                :loading="submitting.emailBtn"
                            >
                                登录
                            </a-button>
                        </a-form-item>
                    </a-form>
                </a-tab-pane>

                <!-- 手机号登录 -->
                <a-tab-pane key="phone" tab="手机号登录">
                    <a-form
                        ref="phoneFormRef"
                        :model="phoneForm"
                        @finish="handlePhoneSubmit"
                        :label-col="labelCol"
                        :wrapper-col="wrapperCol"
                    >
                        <a-form-item name="userPhone" :rules="FormRules.userPhone">
                            <a-input
                                v-model:value="phoneForm.userPhone"
                                size="large"
                                placeholder="请输入手机号"
                                allow-clear
                            >
                                <template #prefix><MobileOutlined /></template>
                            </a-input>
                        </a-form-item>
                        <a-form-item name="captchaCode" :rules="FormRules.captchaCode">
                            <div class="captcha-wrapper">
                                <a-input
                                    v-model:value="phoneForm.captchaCode"
                                    size="large"
                                    placeholder="请输入验证码"
                                    allow-clear
                                >
                                    <template #prefix><SafetyCertificateOutlined /></template>
                                </a-input>
                                <a-button
                                    size="large"
                                    :disabled="phoneCaptchaSender.countdown.value > 0"
                                    :loading="phoneCaptchaSender.sending.value"
                                    @click="phoneCaptchaSender.send()"
                                >
                                    {{
                                        phoneCaptchaSender.countdown.value > 0
                                            ? `${phoneCaptchaSender.countdown.value}秒后重试`
                                            : "获取验证码"
                                    }}
                                </a-button>
                            </div>
                        </a-form-item>
                        <a-form-item>
                            <a-button
                                type="primary"
                                html-type="submit"
                                size="large"
                                block
                                :loading="submitting.phoneBtn"
                            >
                                登录
                            </a-button>
                        </a-form-item>
                    </a-form>
                </a-tab-pane>
            </a-tabs>
        </a-card>
        <!-- 忘记密码弹窗 -->
        <a-modal
            v-model:visible="showResetModal"
            title="重置密码"
            :destroyOnClose="true"
            :footer="null"
            width="520px"
            @cancel="() => (showResetModal = false)"
        >
            <a-tabs v-model:activeKey="resetActiveKey" centered>
                <a-tab-pane key="email" tab="邮箱重置">
                    <a-form
                        ref="emailResetFormRef"
                        :model="emailResetForm"
                        @finish="handleEmailResetSubmit"
                        :label-col="labelCol"
                        :wrapper-col="wrapperCol"
                    >
                        <a-form-item name="userEmail" :rules="emailResetRules.userEmail">
                            <a-input
                                v-model:value="emailResetForm.userEmail"
                                size="large"
                                placeholder="请输入邮箱地址"
                                allow-clear
                            >
                                <template #prefix><MailOutlined /></template>
                            </a-input>
                        </a-form-item>

                        <a-form-item name="captchaCode" :rules="emailResetRules.captchaCode">
                            <div class="captcha-wrapper">
                                <a-input
                                    v-model:value="emailResetForm.captchaCode"
                                    size="large"
                                    placeholder="请输入验证码"
                                    allow-clear
                                >
                                    <template #prefix><SafetyCertificateOutlined /></template>
                                </a-input>
                                <a-button
                                    size="large"
                                    :disabled="emailResetCaptchaSender.countdown.value > 0"
                                    :loading="emailResetCaptchaSender.sending.value"
                                    @click="emailResetCaptchaSender.send()"
                                >
                                    {{
                                        emailResetCaptchaSender.countdown.value > 0
                                            ? `${emailResetCaptchaSender.countdown.value}秒后重试`
                                            : "获取验证码"
                                    }}
                                </a-button>
                            </div>
                        </a-form-item>

                        <a-form-item name="newPassword" :rules="emailResetRules.newPassword">
                            <a-input-password
                                v-model:value="emailResetForm.newPassword"
                                size="large"
                                placeholder="请输入新密码"
                                allow-clear
                            >
                                <template #prefix><LockOutlined /></template>
                            </a-input-password>
                        </a-form-item>

                        <a-form-item name="checkPassword" :rules="emailResetRules.checkPassword">
                            <a-input-password
                                v-model:value="emailResetForm.checkPassword"
                                size="large"
                                placeholder="确认新密码"
                                allow-clear
                            >
                                <template #prefix><LockOutlined /></template>
                            </a-input-password>
                        </a-form-item>

                        <a-form-item>
                            <a-button
                                type="primary"
                                html-type="submit"
                                size="large"
                                block
                                :loading="submitting.emailResetBtn"
                                >确定</a-button
                            >
                        </a-form-item>
                    </a-form>
                </a-tab-pane>

                <a-tab-pane key="phone" tab="手机号重置">
                    <a-form
                        ref="phoneResetFormRef"
                        :model="phoneResetForm"
                        @finish="handlePhoneResetSubmit"
                        :label-col="labelCol"
                        :wrapper-col="wrapperCol"
                    >
                        <a-form-item name="userPhone" :rules="phoneResetRules.userPhone">
                            <a-input
                                v-model:value="phoneResetForm.userPhone"
                                size="large"
                                placeholder="请输入手机号"
                                allow-clear
                            >
                                <template #prefix><MobileOutlined /></template>
                            </a-input>
                        </a-form-item>

                        <a-form-item name="captchaCode" :rules="phoneResetRules.captchaCode">
                            <div class="captcha-wrapper">
                                <a-input
                                    v-model:value="phoneResetForm.captchaCode"
                                    size="large"
                                    placeholder="请输入验证码"
                                    allow-clear
                                >
                                    <template #prefix><SafetyCertificateOutlined /></template>
                                </a-input>
                                <a-button
                                    size="large"
                                    :disabled="phoneResetCaptchaSender.countdown.value > 0"
                                    :loading="phoneResetCaptchaSender.sending.value"
                                    @click="phoneResetCaptchaSender.send()"
                                >
                                    {{
                                        phoneResetCaptchaSender.countdown.value > 0
                                            ? `${phoneResetCaptchaSender.countdown.value}秒后重试`
                                            : "获取验证码"
                                    }}
                                </a-button>
                            </div>
                        </a-form-item>

                        <a-form-item name="newPassword" :rules="phoneResetRules.newPassword">
                            <a-input-password
                                v-model:value="phoneResetForm.newPassword"
                                size="large"
                                placeholder="请输入新密码"
                                allow-clear
                            >
                                <template #prefix><LockOutlined /></template>
                            </a-input-password>
                        </a-form-item>

                        <a-form-item name="checkPassword" :rules="phoneResetRules.checkPassword">
                            <a-input-password
                                v-model:value="phoneResetForm.checkPassword"
                                size="large"
                                placeholder="确认新密码"
                                allow-clear
                            >
                                <template #prefix><LockOutlined /></template>
                            </a-input-password>
                        </a-form-item>

                        <a-form-item>
                            <a-button
                                type="primary"
                                html-type="submit"
                                size="large"
                                block
                                :loading="submitting.phoneResetBtn"
                                >确定</a-button
                            >
                        </a-form-item>
                    </a-form>
                </a-tab-pane>
            </a-tabs>
        </a-modal>
    </div>
</template>

<style scoped>
#user-login {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
}

.login-card {
    min-width: 430px;
    box-shadow: 0 2px 8px rgb(0 0 0 / 10%);
}

.captcha-wrapper {
    display: flex;
    gap: 8px;
}

.captcha-wrapper .ant-input-affix-wrapper {
    flex: 1;
}

.login-footer {
    text-align: center;
}
</style>

// user-center-react-frontend/src/pages/auth/login/index.tsx
import {
  LockOutlined,
  MailOutlined,
  MobileOutlined,
  SafetyCertificateOutlined,
  UserOutlined,
} from "@ant-design/icons";
import {
  LoginForm,
  ProFormCaptcha,
  ProFormText,
} from "@ant-design/pro-components";
import { Helmet, history } from "@umijs/max";
import { App, Button, Form, Input, Modal, Tabs } from "antd";
import { createStyles } from "antd-style";
import React, { useState } from "react";
import { Footer } from "@/components";
import {
  BusinessCode,
  CODE_REGEX,
  PASSWORD_MAX_LENGTH,
  PASSWORD_MIN_LENGTH,
  PHONE_REGEX,
  PWD_REGEX,
  ROUTES,
  SYSTEM_LOGO,
  SYSTEM_SUBTITLE,
  SYSTEM_TITLE,
} from "@/constants";
import { useCaptchaSender } from "@/hooks/useCaptchaSender";
import { sendCaptcha } from "@/services/ant-design-pro/captcha";
import {
  userEmailLogin,
  userLogin,
  userPhoneLogin,
  userPhoneResetPwd,
  userResetPwd,
} from "@/services/ant-design-pro/user";
import { authStore } from "@/stores/auth";
import { getSafeAuthRedirect } from "@/utils/redirect/auth-redirect";
import Settings from "../../../../config/defaultSettings";

const useStyles = createStyles(({ token }) => {
  return {
    action: {
      marginLeft: "8px",
      color: "rgba(0, 0, 0, 0.2)",
      fontSize: "24px",
      verticalAlign: "middle",
      cursor: "pointer",
      transition: "color 0.3s",
      "&:hover": {
        color: token.colorPrimaryActive,
      },
    },
    lang: {
      width: 42,
      height: 42,
      lineHeight: "42px",
      position: "fixed" as const,
      right: 16,
      borderRadius: token.borderRadius,
      ":hover": {
        backgroundColor: token.colorBgTextHover,
      },
    },
    container: {
      display: "flex",
      flexDirection: "column",
      height: "100vh",
      overflow: "auto",
      backgroundImage:
        "url('https://mdn.alipayobjects.com/yuyan_qk0oxh/afts/img/V-_oS6r-i7wAAAAAAAAAAAAAFl94AQBr')",
      backgroundSize: "100% 100%",
    },
    captchaWrapper: {
      display: "flex",
      gap: 8,
    },
  };
});

const Login: React.FC = () => {
  const [type, setType] = useState<string>("account");
  const { styles } = useStyles();
  const { message } = App.useApp();

  // Forgot password modal state
  const [showResetModal, setShowResetModal] = useState(false);
  const [resetActiveKey, setResetActiveKey] = useState<string>("email");
  const [emailResetForm] = Form.useForm();
  const [phoneResetForm] = Form.useForm();
  const [resetSubmitting, setResetSubmitting] = useState({
    emailBtn: false,
    phoneBtn: false,
  });

  // Forgot password captcha senders (RESET_PWD scene)
  const emailResetCaptchaSender = useCaptchaSender(
    "EMAIL",
    "RESET_PWD",
    () => emailResetForm.getFieldValue("userEmail"),
    "请输入邮箱地址以获取验证码",
  );

  const phoneResetCaptchaSender = useCaptchaSender(
    "SMS",
    "RESET_PWD",
    () => phoneResetForm.getFieldValue("userPhone"),
    "请输入手机号以获取验证码",
  );

  const handleSubmit = async (
    values:
      | API.UserLoginRequest
      | API.UserEmailLoginRequest
      | API.UserPhoneLoginRequest,
  ) => {
    try {
      let msg = null;
      switch (type) {
        case "account":
          msg = await userLogin({ ...(values as API.UserLoginRequest) });
          break;
        case "email":
          msg = await userEmailLogin({
            ...(values as API.UserEmailLoginRequest),
          });
          break;
        case "phone":
          msg = await userPhoneLogin({
            ...(values as API.UserPhoneLoginRequest),
          });
          break;
        default:
          break;
      }
      if (msg && msg.code === 20000 && msg.success && msg.data) {
        const defaultLoginSuccessMessage = "登录成功！";
        message.success(defaultLoginSuccessMessage);
        authStore.markAuthenticated(msg.data);
        const redirect = new URLSearchParams(window.location.search).get(
          "redirect",
        );
        history.replace(getSafeAuthRedirect(redirect));
        return;
      }
    } catch (error) {
      const defaultLoginFailureMessage = "登录失败，请重试！";
      console.log(error);
      message.error(defaultLoginFailureMessage);
    }
  };

  const handleEmailResetSubmit = async () => {
    setResetSubmitting((prev) => ({ ...prev, emailBtn: true }));
    try {
      const values = await emailResetForm.validateFields();
      const payload: API.UserEmailResetPwdRequest = {
        userEmail: values.userEmail,
        captchaCode: values.captchaCode,
        newPassword: values.newPassword,
        checkPassword: values.checkPassword,
      };
      const response = await userResetPwd(payload);
      if (response.code === BusinessCode.SUCCESS && response.success) {
        message.success("密码重置成功！请使用新密码登录");
        setShowResetModal(false);
        emailResetForm.resetFields();
      }
    } catch (error) {
      console.log("重置密码异常：", error);
    } finally {
      setResetSubmitting((prev) => ({ ...prev, emailBtn: false }));
    }
  };

  const handlePhoneResetSubmit = async () => {
    setResetSubmitting((prev) => ({ ...prev, phoneBtn: true }));
    try {
      const values = await phoneResetForm.validateFields();
      const payload: API.UserPhoneResetPwdRequest = {
        userPhone: values.userPhone,
        captchaCode: values.captchaCode,
        newPassword: values.newPassword,
        checkPassword: values.checkPassword,
      };
      const response = await userPhoneResetPwd(payload);
      if (response.code === BusinessCode.SUCCESS && response.success) {
        message.success("密码重置成功！请使用新密码登录");
        setShowResetModal(false);
        phoneResetForm.resetFields();
      }
    } catch (error) {
      console.log("重置密码异常：", error);
    } finally {
      setResetSubmitting((prev) => ({ ...prev, phoneBtn: false }));
    }
  };

  const handleResetModalCancel = () => {
    setShowResetModal(false);
    emailResetForm.resetFields();
    phoneResetForm.resetFields();
  };

  return (
    <div className={styles.container}>
      <Helmet>
        <title>
          登录
          {Settings.title && ` - ${Settings.title}`}
        </title>
      </Helmet>
      <div
        style={{
          flex: "1",
          padding: "32px 0",
        }}
      >
        <LoginForm
          contentStyle={{
            minWidth: 280,
            maxWidth: "75vw",
          }}
          logo={<img alt="logo" src={SYSTEM_LOGO} />}
          title={SYSTEM_TITLE}
          subTitle={SYSTEM_SUBTITLE}
          onFinish={async (values) => {
            await handleSubmit(values as API.UserLoginRequest);
          }}
        >
          <Tabs
            activeKey={type}
            onChange={setType}
            centered
            items={[
              { key: "account", label: "账户密码登录" },
              { key: "email", label: "邮箱登录" },
              { key: "mobile", label: "手机号登录" },
            ]}
          />

          {type === "account" && (
            <>
              <ProFormText
                name="userAccount"
                fieldProps={{
                  size: "large",
                  prefix: <UserOutlined />,
                }}
                placeholder={"请输入登录账号"}
                rules={[
                  { required: true, message: "用户名是必填项！" },
                  { min: 4, type: "string", message: "账号长度不小于 4 位！" },
                  {
                    max: 16,
                    type: "string",
                    message: "账号长度不大于 16 位！",
                  },
                ]}
              />
              <ProFormText.Password
                name="userPassword"
                fieldProps={{
                  size: "large",
                  prefix: <LockOutlined />,
                }}
                placeholder={"请输入登录密码"}
                rules={[
                  { required: true, message: "密码是必填项！" },
                  {
                    min: 8,
                    type: "string",
                    message: "登录密码长度不小于 8 位！",
                  },
                  {
                    max: 20,
                    type: "string",
                    message: "登录密码长度不大于 20 位!",
                  },
                ]}
              />
            </>
          )}

          {type === "email" && (
            <>
              <ProFormText
                fieldProps={{
                  size: "large",
                  prefix: <MailOutlined />,
                }}
                name="userEmail"
                placeholder={"请输入邮箱"}
                rules={[
                  { required: true, message: "邮箱是必填项！" },
                  { type: "email", message: "不合法的邮箱！" },
                ]}
              />
              <ProFormCaptcha
                fieldProps={{
                  size: "large",
                  prefix: <SafetyCertificateOutlined />,
                }}
                captchaProps={{ size: "large" }}
                placeholder={"请输入验证码"}
                captchaTextRender={(timing, count) => {
                  if (timing) return `${count} 秒后重新获取`;
                  return "获取验证码";
                }}
                name="captchaCode"
                phoneName="userEmail"
                rules={[
                  { required: true, message: "验证码是必填项！" },
                  { pattern: /^\d{6}$/, message: "验证码格式不正确" },
                ]}
                onGetCaptcha={async (email) => {
                  const result = await sendCaptcha({
                    type: "EMAIL",
                    scene: "LOGIN",
                    target: email,
                  });
                  if (result.code === 20000 && result.success) {
                    message.success("获取验证码成功！");
                  }
                }}
              />
            </>
          )}

          {type === "mobile" && (
            <>
              <ProFormText
                fieldProps={{
                  size: "large",
                  prefix: <MobileOutlined />,
                }}
                name="userPhone"
                placeholder={"请输入手机号"}
                rules={[
                  { required: true, message: "手机号是必填项！" },
                  { pattern: /^1[3-9]\d{9}$/, message: "不合法的手机号！" },
                ]}
              />
              <ProFormCaptcha
                fieldProps={{
                  size: "large",
                  prefix: <SafetyCertificateOutlined />,
                }}
                captchaProps={{ size: "large" }}
                placeholder={"请输入验证码"}
                captchaTextRender={(timing, count) => {
                  if (timing) return `${count} 秒后重新获取`;
                  return "获取验证码";
                }}
                name="captchaCode"
                phoneName="userPhone"
                rules={[
                  { required: true, message: "验证码是必填项！" },
                  { pattern: /^\d{6}$/, message: "验证码格式不正确" },
                ]}
                onGetCaptcha={async (phone) => {
                  const result = await sendCaptcha({
                    type: "SMS",
                    scene: "LOGIN",
                    target: phone,
                  });
                  if (result.code === 20000 && result.success) {
                    message.success("获取验证码成功！");
                  }
                }}
              />
            </>
          )}
          <div style={{ marginBottom: 24 }}>
            <a
              onClick={(e) => {
                e.preventDefault();
                history.push(ROUTES.REGISTER.path);
              }}
            >
              去注册
            </a>
            <a
              style={{ float: "right" }}
              onClick={(e) => {
                e.preventDefault();
                setShowResetModal(true);
              }}
            >
              忘记密码 ?
            </a>
          </div>
        </LoginForm>
      </div>
      <Footer />

      {/* Forgot Password Modal */}
      <Modal
        open={showResetModal}
        title="重置密码"
        onCancel={handleResetModalCancel}
        destroyOnClose
        footer={null}
        width={520}
      >
        <Tabs
          activeKey={resetActiveKey}
          onChange={setResetActiveKey}
          centered
          items={[
            { key: "email", label: "邮箱重置" },
            { key: "phone", label: "手机号重置" },
          ]}
        />

        {resetActiveKey === "email" && (
          <Form
            form={emailResetForm}
            onFinish={handleEmailResetSubmit}
            labelCol={{ span: 0 }}
            wrapperCol={{ span: 24 }}
          >
            <Form.Item
              name="userEmail"
              rules={[
                { required: true, message: "邮箱地址是必填项!" },
                { type: "email", message: "邮箱格式不正确!" },
              ]}
            >
              <Input
                size="large"
                placeholder="请输入邮箱地址"
                prefix={<MailOutlined />}
                allowClear
              />
            </Form.Item>
            <Form.Item
              name="captchaCode"
              rules={[
                { required: true, message: "验证码是必填项!" },
                { pattern: CODE_REGEX, message: "验证码格式不正确!" },
              ]}
            >
              <div className={styles.captchaWrapper}>
                <Input
                  size="large"
                  placeholder="请输入验证码"
                  prefix={<SafetyCertificateOutlined />}
                  allowClear
                  style={{ flex: 1 }}
                />
                <Button
                  size="large"
                  disabled={emailResetCaptchaSender.countdown > 0}
                  loading={emailResetCaptchaSender.sending}
                  onClick={emailResetCaptchaSender.send}
                >
                  {emailResetCaptchaSender.countdown > 0
                    ? `${emailResetCaptchaSender.countdown}秒后重试`
                    : "获取验证码"}
                </Button>
              </div>
            </Form.Item>
            <Form.Item
              name="newPassword"
              rules={[
                { required: true, message: "新密码是必填项!" },
                {
                  min: PASSWORD_MIN_LENGTH,
                  message: `密码长度不小于 ${PASSWORD_MIN_LENGTH} 位!`,
                },
                {
                  max: PASSWORD_MAX_LENGTH,
                  message: `密码长度不大于 ${PASSWORD_MAX_LENGTH} 位!`,
                },
                {
                  pattern: PWD_REGEX,
                  message: "密码需包含大小写字母、数字和特殊字符",
                },
              ]}
            >
              <Input.Password
                size="large"
                placeholder="请输入新密码"
                prefix={<LockOutlined />}
                allowClear
              />
            </Form.Item>
            <Form.Item
              name="checkPassword"
              dependencies={["newPassword"]}
              rules={[
                { required: true, message: "请确认新密码!" },
                ({ getFieldValue }) => ({
                  validator(_, value) {
                    if (!value || getFieldValue("newPassword") === value) {
                      return Promise.resolve();
                    }
                    return Promise.reject(new Error("两次输入的密码不一致!"));
                  },
                }),
              ]}
            >
              <Input.Password
                size="large"
                placeholder="确认新密码"
                prefix={<LockOutlined />}
                allowClear
              />
            </Form.Item>
            <Form.Item>
              <Button
                type="primary"
                htmlType="submit"
                size="large"
                block
                loading={resetSubmitting.emailBtn}
              >
                确定
              </Button>
            </Form.Item>
          </Form>
        )}

        {resetActiveKey === "phone" && (
          <Form
            form={phoneResetForm}
            onFinish={handlePhoneResetSubmit}
            labelCol={{ span: 0 }}
            wrapperCol={{ span: 24 }}
          >
            <Form.Item
              name="userPhone"
              rules={[
                { required: true, message: "手机号是必填项!" },
                { pattern: PHONE_REGEX, message: "手机号格式不正确!" },
              ]}
            >
              <Input
                size="large"
                placeholder="请输入手机号"
                prefix={<MobileOutlined />}
                allowClear
              />
            </Form.Item>
            <Form.Item
              name="captchaCode"
              rules={[
                { required: true, message: "验证码是必填项!" },
                { pattern: CODE_REGEX, message: "验证码格式不正确!" },
              ]}
            >
              <div className={styles.captchaWrapper}>
                <Input
                  size="large"
                  placeholder="请输入验证码"
                  prefix={<SafetyCertificateOutlined />}
                  allowClear
                  style={{ flex: 1 }}
                />
                <Button
                  size="large"
                  disabled={phoneResetCaptchaSender.countdown > 0}
                  loading={phoneResetCaptchaSender.sending}
                  onClick={phoneResetCaptchaSender.send}
                >
                  {phoneResetCaptchaSender.countdown > 0
                    ? `${phoneResetCaptchaSender.countdown}秒后重试`
                    : "获取验证码"}
                </Button>
              </div>
            </Form.Item>
            <Form.Item
              name="newPassword"
              rules={[
                { required: true, message: "新密码是必填项!" },
                {
                  min: PASSWORD_MIN_LENGTH,
                  message: `密码长度不小于 ${PASSWORD_MIN_LENGTH} 位!`,
                },
                {
                  max: PASSWORD_MAX_LENGTH,
                  message: `密码长度不大于 ${PASSWORD_MAX_LENGTH} 位!`,
                },
                {
                  pattern: PWD_REGEX,
                  message: "密码需包含大小写字母、数字和特殊字符",
                },
              ]}
            >
              <Input.Password
                size="large"
                placeholder="请输入新密码"
                prefix={<LockOutlined />}
                allowClear
              />
            </Form.Item>
            <Form.Item
              name="checkPassword"
              dependencies={["newPassword"]}
              rules={[
                { required: true, message: "请确认新密码!" },
                ({ getFieldValue }) => ({
                  validator(_, value) {
                    if (!value || getFieldValue("newPassword") === value) {
                      return Promise.resolve();
                    }
                    return Promise.reject(new Error("两次输入的密码不一致!"));
                  },
                }),
              ]}
            >
              <Input.Password
                size="large"
                placeholder="确认新密码"
                prefix={<LockOutlined />}
                allowClear
              />
            </Form.Item>
            <Form.Item>
              <Button
                type="primary"
                htmlType="submit"
                size="large"
                block
                loading={resetSubmitting.phoneBtn}
              >
                确定
              </Button>
            </Form.Item>
          </Form>
        )}
      </Modal>
    </div>
  );
};

export default Login;
