// user-center-vue-frontend/src/views/user/settings/moudels/basic-info.vue
<script setup lang="ts">
/**
 * 基本信息卡片
 */
import { UserOutlined } from "@ant-design/icons-vue";
import { useAuthStore } from "@/stores/auth.ts";
import { storeToRefs } from "pinia";
import { reactive, ref, watch } from "vue";
import type { Api } from "@/types/api/typings";
import type { FormInstance } from "ant-design-vue";
import type { Rule } from "ant-design-vue/es/form";
import { messageUtils } from "@/utils/message";
import { formDataValidate } from "@/utils/form/form-data-validate.ts";
import { userUpdateInfo } from "@/api/user.ts";
import { BusinessCode } from "@/constants";

defineOptions({ name: "BasicInfo" });

const authStore = useAuthStore();
// storeToRefs 解构后仍保持响应性
const { user: loginUser } = storeToRefs(authStore);

const labelCol = { span: 0 };
const wrapperCol = { span: 24 };

// 提交按钮状态
const submitting = ref(false);

// 更新基本信息表单引用
const updateInfoFormRef = ref<FormInstance>();

// 更新基本信息表单数据
const updateInfoForm = reactive<Api.User.UserUpdateInfoRequest>({
    id: "",
    userName: "",
    userProfile: "",
    userGender: undefined,
});

// 表单验证规则
const FormRules: Record<string, Rule[]> = {
    userName: [{ max: 20, message: "昵称长度不超过 20 个字符" }],
    userProfile: [{ max: 200, message: "简介长度不超过 200 个字符" }],
};

/**
 * 处理更新基本信息的请求
 */
const handleUpdateInfo = async () => {
    if (!loginUser.value?.id) {
        messageUtils.error("用户信息不存在");
        return;
    }
    // 表单数据验证
    const validated = await formDataValidate(updateInfoFormRef.value!);
    if (!validated) {
        return;
    }
    submitting.value = true;
    try {
        updateInfoForm.id = loginUser.value.id;
        const { data } = await userUpdateInfo(updateInfoForm);
        if (data.code === BusinessCode.SUCCESS && data.success) {
            // 更新成功后刷新用户信息以显示最新的基本信息
            await authStore.refreshCurrentUser();
        }
    } catch (error) {
        console.error("更新基本信息失败:", error);
    } finally {
        submitting.value = false;
    }
};

// 监听登录用户信息变化，自动填充表单中的基本信息字段
watch(
    () => loginUser.value,
    (user) => {
        if (!user) {
            return;
        }
        updateInfoForm.id = user.id || "";
        updateInfoForm.userName = user.userName || "";
        updateInfoForm.userProfile = user.userProfile || "";
        updateInfoForm.userGender = user.userGender;
    },
    { immediate: true }
);
</script>

<template>
    <a-card :bordered="true">
        <template #title>
            <a-space>
                <UserOutlined class="card-icon" />
                <span class="card-title">基本信息</span>
            </a-space>
        </template>
        <a-form
            ref="updateInfoFormRef"
            layout="vertical"
            :model="updateInfoForm"
            @finish="handleUpdateInfo"
            :label-col="labelCol"
            :wrapper-col="wrapperCol"
        >
            <a-form-item label="昵称" name="userName" :rules="FormRules.userName">
                <a-input v-model:value="updateInfoForm.userName" placeholder="请输入昵称" size="large" allow-clear />
            </a-form-item>
            <a-form-item label="性别" name="userGender">
                <a-select v-model:value="updateInfoForm.userGender" placeholder="请选择性别" size="large" allow-clear>
                    <a-select-option :value="0">女</a-select-option>
                    <a-select-option :value="1">男</a-select-option>
                    <a-select-option :value="2">未知</a-select-option>
                </a-select>
            </a-form-item>
            <a-form-item label="简介" name="userProfile" :rules="FormRules.userProfile">
                <a-textarea
                    v-model:value="updateInfoForm.userProfile"
                    placeholder="介绍一下自己"
                    size="large"
                    :auto-size="{ minRows: 3, maxRows: 5 }"
                    allow-clear
                />
            </a-form-item>
            <a-button type="primary" html-type="submit" size="large" block :loading="submitting">
                修改基本信息
            </a-button>
        </a-form>
    </a-card>
</template>

<style scoped>
.card-icon {
    font-size: 16px;
    color: var(--ant-color-primary);
}

.card-title {
    font-size: 16px;
    font-weight: 600;
}
</style>

// user-center-react-frontend/src/pages/user/settings/components/BasicInfo.tsx
import { UserOutlined } from "@ant-design/icons";
import { useModel } from "@umijs/max";
import { App, Button, Card, Form, Input, Select, Space } from "antd";
import { createStyles } from "antd-style";
import React, { useEffect, useState } from "react";
import { BusinessCode } from "@/constants/code";
import { userUpdateInfo } from "@/services/ant-design-pro/user";
import { authStore } from "@/stores/auth";

const useStyles = createStyles(({ token }) => ({
  cardIcon: {
    fontSize: 16,
    color: token.colorPrimary,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: 600,
  },
}));

const BasicInfo: React.FC = () => {
  const { initialState } = useModel("@@initialState");
  const currentUser = initialState?.auth?.user;
  const [form] = Form.useForm();
  const [submitting, setSubmitting] = useState(false);
  const { styles } = useStyles();
  const { message } = App.useApp();

  useEffect(() => {
    if (currentUser) {
      form.setFieldsValue({
        userName: currentUser.userName || "",
        userGender: currentUser.userGender,
        userProfile: currentUser.userProfile || "",
      });
    }
  }, [currentUser, form]);

  const handleUpdateInfo = async () => {
    if (!currentUser?.id) {
      message.error("用户信息不存在");
      return;
    }
    setSubmitting(true);
    try {
      const values = await form.validateFields();
      const response = await userUpdateInfo({
        id: currentUser.id,
        ...values,
      });
      if (response.code === BusinessCode.SUCCESS && response.success) {
        message.success("基本信息更新成功");
        await authStore.refreshCurrentUser();
      }
    } catch (error) {
      console.error("更新基本信息失败:", error);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Card bordered>
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: 8,
          marginBottom: 4,
        }}
      >
        <UserOutlined className={styles.cardIcon} />
        <span className={styles.cardTitle}>基本信息</span>
      </div>
      <Form
        form={form}
        layout="vertical"
        onFinish={handleUpdateInfo}
        labelCol={{ span: 0 }}
        wrapperCol={{ span: 24 }}
      >
        <Form.Item
          label="昵称"
          name="userName"
          rules={[{ max: 20, message: "昵称长度不超过 20 个字符" }]}
        >
          <Input placeholder="请输入昵称" size="large" allowClear />
        </Form.Item>
        <Form.Item label="性别" name="userGender">
          <Select placeholder="请选择性别" size="large" allowClear>
            <Select.Option value={0}>女</Select.Option>
            <Select.Option value={1}>男</Select.Option>
            <Select.Option value={2}>未知</Select.Option>
          </Select>
        </Form.Item>
        <Form.Item
          label="简介"
          name="userProfile"
          rules={[{ max: 200, message: "简介长度不超过 200 个字符" }]}
        >
          <Input.TextArea
            placeholder="介绍一下自己"
            size="large"
            autoSize={{ minRows: 3, maxRows: 5 }}
            allowClear
          />
        </Form.Item>
        <Button
          type="primary"
          htmlType="submit"
          size="large"
          block
          loading={submitting}
        >
          修改基本信息
        </Button>
      </Form>
    </Card>
  );
};

export default BasicInfo;
