// user-center-vue-frontend/src/views/auth/register/index.vue
<script setup lang="ts">
import { ref, reactive } from "vue";
import { useRouter } from "vue-router";
import { userRegister, userEmailRegister, userPhoneRegister } from "@/api/user";
import {
    UserOutlined,
    LockOutlined,
    MailOutlined,
    MobileOutlined,
    SafetyCertificateOutlined,
} from "@ant-design/icons-vue";
import type { Api } from "@/types/api/typings";
import type { Rule } from "ant-design-vue/es/form";
import { ROUTES } from "@/constants/routes.ts";
import type { AxiosResponse } from "axios";
import {
    BusinessCode,
    CODE_REGEX,
    PASSWORD_MAX_LENGTH,
    PASSWORD_MIN_LENGTH,
    PHONE_REGEX,
    PWD_REGEX,
} from "@/constants";
import type { FormInstance } from "ant-design-vue";
import { useCaptchaSender } from "@/composable/send-captcha";

/**
 * 用户注册页面.
 */
defineOptions({ name: "UserRegister" });

const router = useRouter();

const labelCol = { span: 0 };
const wrapperCol = { span: 24 };

// 当前激活的注册方式
const activeKey = ref("account");

// 账号注册表单引用
const accountFormRef = ref<FormInstance>();
// 账号注册表单数据
const accountForm = reactive<Api.User.UserRegisterRequest>({
    userAccount: "",
    userPassword: "",
    checkPassword: "",
});

// 邮箱注册表单引用
const emailFormRef = ref<FormInstance>();
// 邮箱注册表单数据
const emailForm = reactive<Api.User.UserEmailRegisterRequest>({
    userEmail: "",
    captchaCode: "",
    userPassword: "",
    checkPassword: "",
});

// 手机号注册表单引用
const phoneFormRef = ref<FormInstance>();
// 手机号注册表单数据
const phoneForm = reactive<Api.User.UserPhoneRegisterRequest>({
    userPhone: "",
    captchaCode: "",
    userPassword: "",
    checkPassword: "",
});

type SubmitState = {
    accountBtn: boolean;
    emailBtn: boolean;
    phoneBtn: boolean;
};

// 提交按钮状态
const submitting = reactive<SubmitState>({
    accountBtn: false,
    emailBtn: false,
    phoneBtn: false,
});

// 表单验证规则
const FormRules: Record<string, Rule[]> = {
    userAccount: [
        { required: true, message: "登录账号是必填项!", trigger: "blur" },
        { min: 4, message: "账号长度不小于 4 位!", trigger: "blur" },
        { max: 16, message: "账号长度不大于 16 位!", trigger: "blur" },
    ],
    userPassword: [
        { required: true, message: "登录密码是必填项!", trigger: "blur" },
        { min: PASSWORD_MIN_LENGTH, message: `密码长度不小于 ${PASSWORD_MIN_LENGTH} 位!`, trigger: "blur" },
        { max: PASSWORD_MAX_LENGTH, message: `密码长度不大于 ${PASSWORD_MAX_LENGTH} 位!`, trigger: "blur" },
        { pattern: PWD_REGEX, message: "密码需包含大小写字母、数字和特殊字符", trigger: "blur" },
    ],
    checkPassword: [
        { required: true, message: "请确认登录密码!", trigger: "blur" },
        {
            validator: (_rule, value) => {
                if (value !== accountForm.userPassword) {
                    return Promise.reject("两次输入的密码不一致!");
                }
                return Promise.resolve();
            },
            trigger: "blur",
        },
    ],
    userEmail: [
        { required: true, message: "邮箱地址是必填项!", trigger: "blur" },
        { type: "email", message: "邮箱格式不正确!", trigger: "blur" },
    ],
    userPhone: [
        { required: true, message: "手机号是必填项!", trigger: "blur" },
        { pattern: PHONE_REGEX, message: "手机号格式不正确!", trigger: "blur" },
    ],
    captchaCode: [
        { required: true, message: "验证码是必填项!", trigger: "blur" },
        // 验证码格式为 6 位数字
        { pattern: CODE_REGEX, message: "验证码格式不正确!", trigger: "blur" },
    ],
};

type RegisterApiFunction<TRequest> = (data: TRequest) => Promise<AxiosResponse<Api.User.UserRegisterResponse>>;

const createSubmitHandler =
    <TRequest>(
        apiFn: RegisterApiFunction<TRequest>,
        formData: TRequest,
        submitState: SubmitState,
        submitKey: keyof SubmitState
    ) =>
    async () => {
        submitState[submitKey] = true;
        try {
            const { data } = await apiFn(formData);
            if (data.code === BusinessCode.SUCCESS && data.success) {
                await router.push({ name: ROUTES.LOGIN.name });
            }
        } catch (error) {
            console.log(`注册异常：${error}`);
        } finally {
            submitState[submitKey] = false;
        }
    };

/**
 * 处理账号注册提交
 */
const handleAccountSubmit = async () => {
    await accountFormRef.value?.validate();
    await createSubmitHandler(userRegister, accountForm, submitting, "accountBtn")();
};

/**
 * 处理邮箱注册提交
 */
const handleEmailSubmit = async () => {
    emailForm.checkPassword = emailForm.userPassword;
    // 表单校验
    await emailFormRef.value?.validate();
    await createSubmitHandler(userEmailRegister, emailForm, submitting, "emailBtn")();
};

/**
 * 处理手机号注册提交
 */
const handlePhoneSubmit = async () => {
    phoneForm.checkPassword = phoneForm.userPassword;
    await phoneFormRef.value?.validate();
    await createSubmitHandler(userPhoneRegister, phoneForm, submitting, "phoneBtn")();
};

// 邮箱验证码发送器实例
const emailCaptchaSender = useCaptchaSender(
    "EMAIL",
    "REGISTER",
    () => emailForm.userEmail,
    "请输入邮箱地址以获取验证码"
);

// 手机号验证码发送器实例
const phoneCaptchaSender = useCaptchaSender("SMS", "REGISTER", () => phoneForm.userPhone, "请输入手机号以获取验证码");
</script>

<template>
    <div id="user-register">
        <a-card :bordered="false" class="register-card" title="注册新账号">
            <template #extra>
                <div class="register-footer">
                    <span>已有账号？</span>
                    <router-link :to="ROUTES.LOGIN.path">立即登录</router-link>
                </div>
            </template>
            <a-tabs v-model:activeKey="activeKey" centered>
                <!-- 账号注册 -->
                <a-tab-pane key="account" tab="账号密码">
                    <a-form
                        ref="accountFormRef"
                        :model="accountForm"
                        @finish="handleAccountSubmit"
                        :label-col="labelCol"
                        :wrapper-col="wrapperCol"
                    >
                        <a-form-item name="userAccount" :rules="FormRules.userAccount">
                            <a-input
                                v-model:value="accountForm.userAccount"
                                size="large"
                                placeholder="请输入登录账号"
                                allow-clear
                            >
                                <template #prefix><UserOutlined /></template>
                            </a-input>
                        </a-form-item>
                        <a-form-item name="userPassword" :rules="FormRules.userPassword">
                            <a-input-password
                                v-model:value="accountForm.userPassword"
                                size="large"
                                placeholder="请输入登录密码"
                                allow-clear
                            >
                                <template #prefix><LockOutlined /></template>
                            </a-input-password>
                        </a-form-item>
                        <a-form-item name="checkPassword" :rules="FormRules.checkPassword">
                            <a-input-password
                                v-model:value="accountForm.checkPassword"
                                size="large"
                                placeholder="请输入确认密码"
                                allow-clear
                            >
                                <template #prefix><LockOutlined /></template>
                            </a-input-password>
                        </a-form-item>
                        <a-form-item>
                            <a-button
                                type="primary"
                                html-type="submit"
                                size="large"
                                block
                                :loading="submitting.accountBtn"
                            >
                                注册
                            </a-button>
                        </a-form-item>
                    </a-form>
                </a-tab-pane>

                <!-- 邮箱注册 -->
                <a-tab-pane key="email" tab="邮箱注册">
                    <a-form
                        ref="emailFormRef"
                        :model="emailForm"
                        @finish="handleEmailSubmit"
                        :label-col="labelCol"
                        :wrapper-col="wrapperCol"
                    >
                        <a-form-item name="userEmail" :rules="FormRules.userEmail">
                            <a-input
                                v-model:value="emailForm.userEmail"
                                size="large"
                                placeholder="请输入邮箱地址"
                                allow-clear
                            >
                                <template #prefix><MailOutlined /></template>
                            </a-input>
                        </a-form-item>
                        <a-form-item name="captchaCode" :rules="FormRules.captchaCode">
                            <div class="captcha-wrapper">
                                <a-input
                                    v-model:value="emailForm.captchaCode"
                                    size="large"
                                    placeholder="请输入验证码"
                                    allow-clear
                                >
                                    <template #prefix><SafetyCertificateOutlined /></template>
                                </a-input>
                                <a-button
                                    size="large"
                                    :disabled="emailCaptchaSender.countdown.value > 0"
                                    :loading="emailCaptchaSender.sending.value"
                                    @click="emailCaptchaSender.send()"
                                >
                                    {{
                                        emailCaptchaSender.countdown.value > 0
                                            ? `${emailCaptchaSender.countdown.value}秒后重试`
                                            : "获取验证码"
                                    }}
                                </a-button>
                            </div>
                        </a-form-item>
                        <a-form-item name="userPassword" :rules="FormRules.userPassword">
                            <a-input-password
                                v-model:value="emailForm.userPassword"
                                size="large"
                                placeholder="请输入登录密码"
                                allow-clear
                            >
                                <template #prefix><LockOutlined /></template>
                            </a-input-password>
                        </a-form-item>
                        <a-form-item>
                            <a-button
                                type="primary"
                                html-type="submit"
                                size="large"
                                block
                                :loading="submitting.emailBtn"
                            >
                                注册
                            </a-button>
                        </a-form-item>
                    </a-form>
                </a-tab-pane>

                <!-- 手机号注册 -->
                <a-tab-pane key="phone" tab="手机号注册">
                    <a-form
                        ref="phoneFormRef"
                        :model="phoneForm"
                        @finish="handlePhoneSubmit"
                        :label-col="labelCol"
                        :wrapper-col="wrapperCol"
                    >
                        <a-form-item name="userPhone" :rules="FormRules.userPhone">
                            <a-input
                                v-model:value="phoneForm.userPhone"
                                size="large"
                                placeholder="请输入手机号"
                                allow-clear
                            >
                                <template #prefix><MobileOutlined /></template>
                            </a-input>
                        </a-form-item>
                        <a-form-item name="captchaCode" :rules="FormRules.captchaCode">
                            <div class="captcha-wrapper">
                                <a-input
                                    v-model:value="phoneForm.captchaCode"
                                    size="large"
                                    placeholder="请输入验证码"
                                    allow-clear
                                >
                                    <template #prefix><SafetyCertificateOutlined /></template>
                                </a-input>
                                <a-button
                                    size="large"
                                    :disabled="phoneCaptchaSender.countdown.value > 0"
                                    :loading="phoneCaptchaSender.sending.value"
                                    @click="phoneCaptchaSender.send()"
                                >
                                    {{
                                        phoneCaptchaSender.countdown.value > 0
                                            ? `${phoneCaptchaSender.countdown.value}秒后重试`
                                            : "获取验证码"
                                    }}
                                </a-button>
                            </div>
                        </a-form-item>
                        <a-form-item name="userPassword" :rules="FormRules.userPassword">
                            <a-input-password
                                v-model:value="phoneForm.userPassword"
                                size="large"
                                placeholder="请输入登录密码"
                                allow-clear
                            >
                                <template #prefix><LockOutlined /></template>
                            </a-input-password>
                        </a-form-item>
                        <a-form-item>
                            <a-button
                                type="primary"
                                html-type="submit"
                                size="large"
                                block
                                :loading="submitting.phoneBtn"
                            >
                                注册
                            </a-button>
                        </a-form-item>
                    </a-form>
                </a-tab-pane>
            </a-tabs>
        </a-card>
    </div>
</template>

<style scoped>
#user-register {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
}

.register-card {
    min-width: 430px;
    box-shadow: 0 2px 8px rgb(0 0 0 / 10%);
}

.captcha-wrapper {
    display: flex;
    gap: 8px;
}

.captcha-wrapper .ant-input-affix-wrapper {
    flex: 1;
}

.register-footer {
    text-align: center;
}
</style>

// user-center-react-frontend/src/pages/auth/register/index.tsx
import {
  LockOutlined,
  MailOutlined,
  MobileOutlined,
  SafetyCertificateOutlined,
  UserOutlined,
} from "@ant-design/icons";
import { Helmet, history } from "@umijs/max";
import { App, Button, Card, Form, Input, Tabs } from "antd";
import { createStyles } from "antd-style";
import React, { useState } from "react";
import { Footer } from "@/components";
import {
  BusinessCode,
  CODE_REGEX,
  PASSWORD_MAX_LENGTH,
  PASSWORD_MIN_LENGTH,
  PHONE_REGEX,
  PWD_REGEX,
  ROUTES,
  SYSTEM_LOGO,
  SYSTEM_TITLE,
} from "@/constants";
import { useCaptchaSender } from "@/hooks/useCaptchaSender";
import {
  userEmailRegister,
  userPhoneRegister,
  userRegister,
} from "@/services/ant-design-pro/user";
import Settings from "../../../../config/defaultSettings";

const useStyles = createStyles(({ token }) => ({
  container: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    overflow: "auto",
    backgroundImage:
      "url('https://mdn.alipayobjects.com/yuyan_qk0oxh/afts/img/V-_oS6r-i7wAAAAAAAAAAAAAFl94AQBr')",
    backgroundSize: "100% 100%",
  },
  card: {
    minWidth: 430,
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.1)",
  },
  captchaWrapper: {
    display: "flex",
    gap: 8,
  },
  header: {
    textAlign: "center" as const,
    marginBottom: 24,
  },
  logo: {
    height: 44,
    marginRight: 16,
    verticalAlign: "middle",
  },
  title: {
    fontSize: 33,
    color: token.colorTextHeading,
    fontWeight: 600,
  },
}));

const Register: React.FC = () => {
  const [activeKey, setActiveKey] = useState<string>("account");
  const [accountForm] = Form.useForm();
  const [emailForm] = Form.useForm();
  const [phoneForm] = Form.useForm();
  const [submitting, setSubmitting] = useState({
    accountBtn: false,
    emailBtn: false,
    phoneBtn: false,
  });
  const { styles } = useStyles();
  const { message } = App.useApp();

  // Email captcha sender (REGISTER scene)
  const emailCaptchaSender = useCaptchaSender(
    "EMAIL",
    "REGISTER",
    () => emailForm.getFieldValue("userEmail"),
    "请输入邮箱地址以获取验证码",
  );

  // Phone captcha sender (REGISTER scene)
  const phoneCaptchaSender = useCaptchaSender(
    "SMS",
    "REGISTER",
    () => phoneForm.getFieldValue("userPhone"),
    "请输入手机号以获取验证码",
  );

  const handleAccountSubmit = async () => {
    setSubmitting((prev) => ({ ...prev, accountBtn: true }));
    try {
      const values = await accountForm.validateFields();
      const response = await userRegister(values);
      if (response.code === BusinessCode.SUCCESS && response.success) {
        message.success("注册成功！");
        history.push(ROUTES.LOGIN.path);
      }
    } catch (error) {
      console.log("注册异常：", error);
    } finally {
      setSubmitting((prev) => ({ ...prev, accountBtn: false }));
    }
  };

  const handleEmailSubmit = async () => {
    setSubmitting((prev) => ({ ...prev, emailBtn: true }));
    try {
      const values = await emailForm.validateFields();
      const payload = {
        ...values,
        checkPassword: values.userPassword,
      };
      const response = await userEmailRegister(payload);
      if (response.code === BusinessCode.SUCCESS && response.success) {
        message.success("注册成功！");
        history.push(ROUTES.LOGIN.path);
      }
    } catch (error) {
      console.log("注册异常：", error);
    } finally {
      setSubmitting((prev) => ({ ...prev, emailBtn: false }));
    }
  };

  const handlePhoneSubmit = async () => {
    setSubmitting((prev) => ({ ...prev, phoneBtn: true }));
    try {
      const values = await phoneForm.validateFields();
      const payload = {
        ...values,
        checkPassword: values.userPassword,
      };
      const response = await userPhoneRegister(payload);
      if (response.code === BusinessCode.SUCCESS && response.success) {
        message.success("注册成功！");
        history.push(ROUTES.LOGIN.path);
      }
    } catch (error) {
      console.log("注册异常：", error);
    } finally {
      setSubmitting((prev) => ({ ...prev, phoneBtn: false }));
    }
  };

  const handleTabChange = (key: string) => {
    setActiveKey(key);
    accountForm.resetFields();
    emailForm.resetFields();
    phoneForm.resetFields();
  };

  return (
    <div className={styles.container}>
      <Helmet>
        <title>
          注册
          {Settings.title && ` - ${Settings.title}`}
        </title>
      </Helmet>
      <div
        style={{
          flex: "1",
          padding: "32px 0",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <div className={styles.header}>
          <img alt="logo" className={styles.logo} src={SYSTEM_LOGO} />
          <span className={styles.title}>{SYSTEM_TITLE}</span>
        </div>
        <Card
          className={styles.card}
          bordered={false}
          title="注册新账号"
          extra={
            <div style={{ textAlign: "center" }}>
              <span>已有账号？</span>
              <a
                onClick={() => history.push(ROUTES.LOGIN.path)}
                style={{ marginLeft: 8 }}
              >
                立即登录
              </a>
            </div>
          }
        >
          <Tabs
            activeKey={activeKey}
            onChange={handleTabChange}
            centered
            items={[
              { key: "account", label: "账号密码" },
              { key: "email", label: "邮箱注册" },
              { key: "phone", label: "手机号注册" },
            ]}
          />

          {activeKey === "account" && (
            <Form
              form={accountForm}
              onFinish={handleAccountSubmit}
              labelCol={{ span: 0 }}
              wrapperCol={{ span: 24 }}
            >
              <Form.Item
                name="userAccount"
                rules={[
                  { required: true, message: "登录账号是必填项!" },
                  { min: 4, message: "账号长度不小于 4 位!" },
                  { max: 16, message: "账号长度不大于 16 位!" },
                ]}
              >
                <Input
                  size="large"
                  placeholder="请输入登录账号"
                  prefix={<UserOutlined />}
                  allowClear
                />
              </Form.Item>
              <Form.Item
                name="userPassword"
                rules={[
                  { required: true, message: "登录密码是必填项!" },
                  {
                    min: PASSWORD_MIN_LENGTH,
                    message: `密码长度不小于 ${PASSWORD_MIN_LENGTH} 位!`,
                  },
                  {
                    max: PASSWORD_MAX_LENGTH,
                    message: `密码长度不大于 ${PASSWORD_MAX_LENGTH} 位!`,
                  },
                  {
                    pattern: PWD_REGEX,
                    message: "密码需包含大小写字母、数字和特殊字符",
                  },
                ]}
              >
                <Input.Password
                  size="large"
                  placeholder="请输入登录密码"
                  prefix={<LockOutlined />}
                  allowClear
                />
              </Form.Item>
              <Form.Item
                name="checkPassword"
                dependencies={["userPassword"]}
                rules={[
                  { required: true, message: "请确认登录密码!" },
                  ({ getFieldValue }) => ({
                    validator(_, value) {
                      if (!value || getFieldValue("userPassword") === value) {
                        return Promise.resolve();
                      }
                      return Promise.reject(new Error("两次输入的密码不一致!"));
                    },
                  }),
                ]}
              >
                <Input.Password
                  size="large"
                  placeholder="请输入确认密码"
                  prefix={<LockOutlined />}
                  allowClear
                />
              </Form.Item>
              <Form.Item>
                <Button
                  type="primary"
                  htmlType="submit"
                  size="large"
                  block
                  loading={submitting.accountBtn}
                >
                  注册
                </Button>
              </Form.Item>
            </Form>
          )}

          {activeKey === "email" && (
            <Form
              form={emailForm}
              onFinish={handleEmailSubmit}
              labelCol={{ span: 0 }}
              wrapperCol={{ span: 24 }}
            >
              <Form.Item
                name="userEmail"
                rules={[
                  { required: true, message: "邮箱地址是必填项!" },
                  { type: "email", message: "邮箱格式不正确!" },
                ]}
              >
                <Input
                  size="large"
                  placeholder="请输入邮箱地址"
                  prefix={<MailOutlined />}
                  allowClear
                />
              </Form.Item>
              <Form.Item
                name="captchaCode"
                rules={[
                  { required: true, message: "验证码是必填项!" },
                  { pattern: CODE_REGEX, message: "验证码格式不正确!" },
                ]}
              >
                <div className={styles.captchaWrapper}>
                  <Input
                    size="large"
                    placeholder="请输入验证码"
                    prefix={<SafetyCertificateOutlined />}
                    allowClear
                    style={{ flex: 1 }}
                  />
                  <Button
                    size="large"
                    disabled={emailCaptchaSender.countdown > 0}
                    loading={emailCaptchaSender.sending}
                    onClick={emailCaptchaSender.send}
                  >
                    {emailCaptchaSender.countdown > 0
                      ? `${emailCaptchaSender.countdown}秒后重试`
                      : "获取验证码"}
                  </Button>
                </div>
              </Form.Item>
              <Form.Item
                name="userPassword"
                rules={[
                  { required: true, message: "登录密码是必填项!" },
                  {
                    min: PASSWORD_MIN_LENGTH,
                    message: `密码长度不小于 ${PASSWORD_MIN_LENGTH} 位!`,
                  },
                  {
                    max: PASSWORD_MAX_LENGTH,
                    message: `密码长度不大于 ${PASSWORD_MAX_LENGTH} 位!`,
                  },
                  {
                    pattern: PWD_REGEX,
                    message: "密码需包含大小写字母、数字和特殊字符",
                  },
                ]}
              >
                <Input.Password
                  size="large"
                  placeholder="请输入登录密码"
                  prefix={<LockOutlined />}
                  allowClear
                />
              </Form.Item>
              <Form.Item>
                <Button
                  type="primary"
                  htmlType="submit"
                  size="large"
                  block
                  loading={submitting.emailBtn}
                >
                  注册
                </Button>
              </Form.Item>
            </Form>
          )}

          {activeKey === "phone" && (
            <Form
              form={phoneForm}
              onFinish={handlePhoneSubmit}
              labelCol={{ span: 0 }}
              wrapperCol={{ span: 24 }}
            >
              <Form.Item
                name="userPhone"
                rules={[
                  { required: true, message: "手机号是必填项!" },
                  { pattern: PHONE_REGEX, message: "手机号格式不正确!" },
                ]}
              >
                <Input
                  size="large"
                  placeholder="请输入手机号"
                  prefix={<MobileOutlined />}
                  allowClear
                />
              </Form.Item>
              <Form.Item
                name="captchaCode"
                rules={[
                  { required: true, message: "验证码是必填项!" },
                  { pattern: CODE_REGEX, message: "验证码格式不正确!" },
                ]}
              >
                <div className={styles.captchaWrapper}>
                  <Input
                    size="large"
                    placeholder="请输入验证码"
                    prefix={<SafetyCertificateOutlined />}
                    allowClear
                    style={{ flex: 1 }}
                  />
                  <Button
                    size="large"
                    disabled={phoneCaptchaSender.countdown > 0}
                    loading={phoneCaptchaSender.sending}
                    onClick={phoneCaptchaSender.send}
                  >
                    {phoneCaptchaSender.countdown > 0
                      ? `${phoneCaptchaSender.countdown}秒后重试`
                      : "获取验证码"}
                  </Button>
                </div>
              </Form.Item>
              <Form.Item
                name="userPassword"
                rules={[
                  { required: true, message: "登录密码是必填项!" },
                  {
                    min: PASSWORD_MIN_LENGTH,
                    message: `密码长度不小于 ${PASSWORD_MIN_LENGTH} 位!`,
                  },
                  {
                    max: PASSWORD_MAX_LENGTH,
                    message: `密码长度不大于 ${PASSWORD_MAX_LENGTH} 位!`,
                  },
                  {
                    pattern: PWD_REGEX,
                    message: "密码需包含大小写字母、数字和特殊字符",
                  },
                ]}
              >
                <Input.Password
                  size="large"
                  placeholder="请输入登录密码"
                  prefix={<LockOutlined />}
                  allowClear
                />
              </Form.Item>
              <Form.Item>
                <Button
                  type="primary"
                  htmlType="submit"
                  size="large"
                  block
                  loading={submitting.phoneBtn}
                >
                  注册
                </Button>
              </Form.Item>
            </Form>
          )}
        </Card>
      </div>
      <Footer />
    </div>
  );
};

export default Register;
