// user-center-react-frontend/src/pages/admin/manage/components/ViewUserDrawer.tsx
import { Descriptions, Drawer, Image, Spin, Tag } from "antd";
import dayjs from "dayjs";
import React, { useEffect, useState } from "react";
import { DEFAULT_AVATAR } from "@/constants";
import { USER_ROLE, USER_STATUS } from "@/constants/user";
import { useUserOperations } from "@/hooks/useUserOperations";
import GenderDisplay from "@/pages/user/profiles/components/GenderDisplay";

interface ViewUserDrawerProps {
  open: boolean;
  user?: API.UserVo;
  onClose: () => void;
}

const ViewUserDrawer: React.FC<ViewUserDrawerProps> = ({
  open,
  user,
  onClose,
}) => {
  const { handleAdminGetUserById } = useUserOperations();
  const [loading, setLoading] = useState(false);
  const [userDetail, setUserDetail] = useState<API.UserVo | undefined>(user);

  useEffect(() => {
    if (open && user?.id) {
      setLoading(true);
      handleAdminGetUserById(user.id)
        .then((data) => {
          if (data) setUserDetail(data);
        })
        .finally(() => setLoading(false));
    } else {
      setUserDetail(user);
    }
  }, [open, user?.id]);

  const detail = userDetail || user;

  return (
    <Drawer
      title="用户详情"
      open={open}
      onClose={onClose}
      width={600}
      destroyOnClose
    >
      <Spin spinning={loading}>
        <div style={{ textAlign: "center", marginBottom: 24 }}>
          <Image
            src={detail?.userAvatar || DEFAULT_AVATAR}
            alt="avatar"
            width={100}
            height={100}
            style={{ borderRadius: "50%", objectFit: "cover" }}
            fallback={DEFAULT_AVATAR}
          />
        </div>
        <Descriptions bordered column={1} size="middle">
          <Descriptions.Item label="用户 ID">
            {detail?.id || "-"}
          </Descriptions.Item>
          <Descriptions.Item label="登录账号">
            {detail?.userAccount || "-"}
          </Descriptions.Item>
          <Descriptions.Item label="用户昵称">
            {detail?.userName || "未设置"}
          </Descriptions.Item>
          <Descriptions.Item label="用户角色">
            <Tag color={detail?.userRole === USER_ROLE.ADMIN ? "gold" : "blue"}>
              {detail?.userRole === USER_ROLE.ADMIN ? "管理员" : "普通用户"}
            </Tag>
          </Descriptions.Item>
          <Descriptions.Item label="账号状态">
            <Tag
              color={
                detail?.userStatus === USER_STATUS.NORMAL ? "success" : "error"
              }
            >
              {detail?.userStatus === USER_STATUS.NORMAL ? "正常" : "封禁"}
            </Tag>
          </Descriptions.Item>
          <Descriptions.Item label="性别">
            <GenderDisplay gender={detail?.userGender} />
          </Descriptions.Item>
          <Descriptions.Item label="手机号">
            {detail?.userPhone || "未设置"}
          </Descriptions.Item>
          <Descriptions.Item label="邮箱">
            {detail?.userEmail || "未设置"}
          </Descriptions.Item>
          <Descriptions.Item label="个人简介">
            {detail?.userProfile || "未设置"}
          </Descriptions.Item>
          <Descriptions.Item label="创建时间">
            {detail?.createTime
              ? dayjs(detail.createTime).format("YYYY-MM-DD HH:mm:ss")
              : "-"}
          </Descriptions.Item>
          <Descriptions.Item label="更新时间">
            {detail?.updateTime
              ? dayjs(detail.updateTime).format("YYYY-MM-DD HH:mm:ss")
              : "-"}
          </Descriptions.Item>
        </Descriptions>
      </Spin>
    </Drawer>
  );
};

export default ViewUserDrawer;

// user-center-vue-frontend/src/views/user/manage/modules/view-user-drawer.vue
<script setup lang="ts">
/**
 * 用户详情抽屉组件
 */
import type { Api } from "@/types/api/typings";
import { UserOutlined, SafetyOutlined, TeamOutlined } from "@ant-design/icons-vue";
import { computed } from "vue";
import { USER_ROLE, USER_STATUS } from "@/constants/user.ts";
import { formatDateTime } from "@/utils/date";

defineOptions({ name: "ViewUserDrawer" });

const props = defineProps<{
    visible: boolean;
    user: Api.UserAdmin.UserVo | null;
}>();

const emit = defineEmits<{
    (event: "close"): void;
}>();

const handleClose = () => {
    emit("close");
};

const genderText = computed(() => {
    if (!props.user) {
        return "未知";
    }
    switch (props.user.userGender) {
        case 0:
            return "女";
        case 1:
            return "男";
        default:
            return "未知";
    }
});
</script>

<template>
    <a-drawer
        :open="props.visible"
        :width="520"
        destroy-on-close
        placement="right"
        title="用户详情"
        @close="handleClose"
    >
        <div v-if="user" class="drawer-content">
            <div class="profile-section">
                <a-avatar :size="96" :src="user.userAvatar">
                    <template #icon><UserOutlined /> </template>
                </a-avatar>
                <div class="profile-meta">
                    <h3>{{ user.userName || "未设置昵称" }}</h3>
                    <span class="account">@{{ user.userAccount }}</span>
                    <a-tag v-if="user.userRole === USER_ROLE.ADMIN" color="blue"><SafetyOutlined /> 管理员</a-tag>
                    <a-tag v-else color="default"><TeamOutlined /> 普通用户</a-tag>
                </div>
            </div>

            <a-descriptions :column="1" bordered class="info-descriptions" size="middle">
                <a-descriptions-item label="用户编号">
                    <a-typography-text copyable>{{ user.id }}</a-typography-text>
                </a-descriptions-item>
                <a-descriptions-item label="性别">
                    {{ genderText }}
                </a-descriptions-item>
                <a-descriptions-item label="手机号码">
                    {{ user.userPhone || "未填写" }}
                </a-descriptions-item>
                <a-descriptions-item label="邮箱地址">
                    {{ user.userEmail || "未填写" }}
                </a-descriptions-item>
                <a-descriptions-item label="账号状态">
                    <a-badge :status="user.userStatus === USER_STATUS.NORMAL ? 'success' : 'error'" />
                    <span class="status-text">
                        {{ user.userStatus === USER_STATUS.NORMAL ? "正常" : "封禁" }}
                    </span>
                </a-descriptions-item>
                <a-descriptions-item label="用户简介">
                    {{ user.userProfile || "暂无简介" }}
                </a-descriptions-item>
                <a-descriptions-item label="创建时间">
                    {{ formatDateTime(user.createTime) }}
                </a-descriptions-item>
                <a-descriptions-item label="更新时间">
                    {{ formatDateTime(user.updateTime) }}
                </a-descriptions-item>
            </a-descriptions>
        </div>
        <a-empty v-else description="暂无用户信息" />
    </a-drawer>
</template>

<style scoped>
.drawer-content {
    display: flex;
    flex-direction: column;
    gap: 24px;
}

.profile-section {
    display: flex;
    gap: 16px;
    align-items: center;
}

.profile-meta h3 {
    margin: 0;
    font-size: 18px;
    font-weight: 600;
    color: rgb(0 0 0 / 85%);
}

.profile-meta .account {
    display: inline-block;
    margin: 4px 0 8px;
    color: rgb(0 0 0 / 45%);
}

.status-text {
    margin-left: 8px;
}

.info-descriptions :deep(.ant-descriptions-item-label) {
    width: 96px;
}
</style>
